FROM scratch

# Core bundle labels.
LABEL operators.operatorframework.io.bundle.mediatype.v1=registry+v1
LABEL operators.operatorframework.io.bundle.manifests.v1=manifests/
LABEL operators.operatorframework.io.bundle.metadata.v1=metadata/
LABEL operators.operatorframework.io.bundle.package.v1=authorino-operator
LABEL operators.operatorframework.io.bundle.channels.v1=stable
LABEL operators.operatorframework.io.bundle.channel.default.v1=stable

LABEL operators.operatorframework.io.metrics.builder=operator-sdk-v1.33.0
LABEL operators.operatorframework.io.metrics.mediatype.v1=metrics+v1
LABEL operators.operatorframework.io.metrics.project_layout=go.kubebuilder.io/v4

# Labels for testing.
LABEL operators.operatorframework.io.test.mediatype.v1=scorecard+v1
LABEL operators.operatorframework.io.test.config.v1=tests/scorecard/

LABEL version="1.3.1" \
      summary="Enables authentication and authorization for Gateways and applications in a Gateway API network" \
      name="rhcl-1/authorino-operator-bundle" \
      cpe="cpe:/a:redhat:connectivity_link:1::el9" \
      description="Enables authentication and authorization for Gateways and applications in a Gateway API network" \
      io.k8s.display-name="Authorino Operator metadata" \
      io.k8s.description="Enables authentication and authorization for Gateways and applications in a Gateway API network" \
      io.openshift.expose-services="" \
      io.openshift.tags="api" \
      url="" \
      distribution-scope="public" \
      release="1.3.1" \
      com.redhat.component="Red Hat Connectivity Link Operator Bundle" \
      vendor="Red Hat, Inc."

# Copy files to locations specified by labels.
COPY /bundle-stage/manifests /manifests/
COPY /bundle-stage/metadata /metadata/
COPY authorino-operator/bundle/tests/scorecard /tests/scorecard/
