################################
# Red Hat Authorino Operator
################################

FROM registry.redhat.io/ubi9/go-toolset:latest AS builder

ENV BINARY_NAME="manager"

WORKDIR /workspace
# Copy the Go Modules manifests
COPY authorino-operator/go.mod go.mod
COPY authorino-operator/go.sum go.sum
# cache deps before building and copying source so that we don't need to re-download as much
# and so that source changes don't invalidate our downloaded layer
RUN go mod download

# Copy the go source
COPY ./authorino-operator/main.go main.go
COPY ./authorino-operator/api/ api/
COPY ./authorino-operator/controllers/ controllers/
COPY ./authorino-operator/pkg/ pkg/
COPY ./authorino-operator/LICENSE /licenses/LICENSE

# Set environment variables for cross-compilation
ARG TARGETARCH

# Build arguments aligned with upstream
ARG GIT_SHA
ARG DIRTY

ENV GIT_SHA=${GIT_SHA:-unknown}
ENV DIRTY=${DIRTY:-unknown}

# Build Authorino Operator
RUN echo "Building with GIT_SHA=${GIT_SHA}, DIRTY=${DIRTY}" && \
    CGO_ENABLED=0 GOOS=linux GOARCH=${TARGETARCH:-$(go env GOARCH)} go build -a \
    -ldflags "-X main.version=${AUTHORINO_OPERATOR_VERSION} -X main.gitSHA=${GIT_SHA} -X main.dirty=${DIRTY}" \
    -o ${BINARY_NAME} main.go


FROM registry.redhat.io/ubi9/ubi-minimal:latest
LABEL version="0.23.3" \
      com.redhat.component="authorino-operator" \
      name="rhcl-1/authorino-rhel9-operator" \
      cpe="cpe:/a:redhat:connectivity_link:1::el9" \
      release="${AUTHORINO_OPERATOR_VERSION}" \
      url="registry.redhat.io/rhcl-1/authorino-operator" \
      summary="Enables authentication and authorization for Gateways and applications in a Gateway API network." \
      description="Enables authentication and authorization for Gateways and applications in a Gateway API network." \
      io.k8s.description="Authorino Operator" \
      io.k8s.display-name="Authorino Operator" \
      io.openshift.expose-services="" \
      io.openshift.tags="api" \
      vendor="Red Hat, Inc." \
      maintainer="mcassola@redhat.com"

ENV OPERATOR_BINARY_NAME="manager" \
  USER_UID=1001 \
  USER_NAME=authorino-operator

USER root

# install operator binary
COPY --from=builder /workspace/${OPERATOR_BINARY_NAME} /
RUN chown ${USER_UID} /${OPERATOR_BINARY_NAME}

COPY --from=builder licenses/LICENSE ./licenses/LICENSE

# TODO: Install licenses
# ENV LICENSES_DIR="/licenses/apicast-operator/"
# RUN mkdir -p ${LICENSES_DIR}
# COPY authorino-operator/LICENSE ${LICENSES_DIR}
# RUN chown ${USER_UID} ${LICENSES_DIR}/licenses

ENTRYPOINT ["/manager"]

USER ${USER_UID}