apiVersion: config.openshift.io/v1
kind: ImageDigestMirrorSet
metadata:
  name: authorino-operator-mirrors
spec:
  imageDigestMirrors:
    - source: registry.redhat.io/rhcl-1/authorino-rhel9-operator
      mirrors:
        - quay.io/redhat-user-workloads/api-management-tenant/rhcl-1-4-authorino-operator
    - source: registry.redhat.io/rhcl-1/authorino-rhel9
      mirrors:
        - quay.io/redhat-user-workloads/api-management-tenant/rhcl-1-4-authorino
    - source: registry.stage.redhat.io/rhcl-1/authorino-rhel9-operator
      mirrors:
        - quay.io/redhat-user-workloads/api-management-tenant/rhcl-1-4-authorino-operator
    - source: registry.stage.redhat.io/rhcl-1/authorino-rhel9
      mirrors:
        - quay.io/redhat-user-workloads/api-management-tenant/rhcl-1-4-authorino
